steps:
      - name: 'gcr.io/cloud-builders/docker'  
        #Use cloudbuild to build and use -t to exit after running this command
        #path is gcr.io/PROJECT_ID/IMAGE_NAME
        args: ['build','-t','gcr.io/kheopsys-data-lab/hello_world:latest','.']
        
        #Create and store an image in the container registry
images: ['gcr.io/kheopsys-data-lab/hello_world:latest']